import { describe, it, expect } from 'vitest';
import { isAutoGeneratedName, slotDisplayTitle } from './materialSlotLabel';

describe('isAutoGeneratedName', () => {
  it('ツール自動生成のマテリアル名を判定する', () => {
    expect(isAutoGeneratedName('tripo_material_4458bb22-a5be-4ddf-bfe5-fbbd663f9db3')).toBe(true);
    expect(isAutoGeneratedName('tripo_node_4458bb22')).toBe(true);
    expect(isAutoGeneratedName('material_0')).toBe(true);
    expect(isAutoGeneratedName('Material.001')).toBe(true);
    expect(isAutoGeneratedName('material 3')).toBe(true); // applyMaterial.ts の既定名 `material {i}`
    expect(isAutoGeneratedName('mesh_12')).toBe(true);
    expect(isAutoGeneratedName('node_7')).toBe(true);
    expect(isAutoGeneratedName('defaultMaterial')).toBe(true);
  });
  it('人間が付けた名前は自動生成と判定しない', () => {
    expect(isAutoGeneratedName('張地')).toBe(false);
    expect(isAutoGeneratedName('Leather Seat')).toBe(false);
    expect(isAutoGeneratedName('oak_frame')).toBe(false);
    expect(isAutoGeneratedName('')).toBe(false);
  });
});

describe('slotDisplayTitle', () => {
  it('label があれば最優先', () => {
    expect(slotDisplayTitle('張地', 'tripo_material_x', 0)).toBe('張地');
  });
  it('label 無し・自動生成名なら「部位 N」（1始まり）', () => {
    expect(slotDisplayTitle('', 'tripo_material_x', 0)).toBe('部位 1');
    expect(slotDisplayTitle(undefined, 'Material.001', 2)).toBe('部位 3');
  });
  it('label 無し・人間の名前ならそのまま', () => {
    expect(slotDisplayTitle('', 'Leather Seat', 0)).toBe('Leather Seat');
  });
  it('label もマテリアル名も無ければ「部位 N」', () => {
    expect(slotDisplayTitle('', undefined, 1)).toBe('部位 2');
  });
});
