/**
 * GLB 由来のマテリアル/メッシュ名が「ツールの自動生成名」かどうかの判定。
 * 詳細画面の素材編集で `tripo_material_4458bb22…` のような生 ID を
 * そのまま見せないためのヘルパ（表示のみ。保存データには使わない）。
 */
const AUTO_NAME_PATTERNS: RegExp[] = [
  /^tripo_/i, // Tripo 生成 (tripo_material_* / tripo_node_*)
  /^(material|mesh|node|object)[._\s-]?\d+$/i, // Blender/glTF 既定名 (Material.001, mesh_12 …)
  /^defaultMaterial\d*$/i, // glTF ローダーの既定名
  /[0-9a-f]{8}[-_][0-9a-f]{4}[-_][0-9a-f]{4}/i, // UUID 断片を含む
];

export const isAutoGeneratedName = (name: string): boolean => {
  const n = (name || '').trim();
  if (!n) return false;
  return AUTO_NAME_PATTERNS.some((re) => re.test(n));
};

/** 素材スロット行の表示タイトル。label > 人間らしいマテリアル名 > 「部位 N」。 */
export const slotDisplayTitle = (
  label: string | undefined,
  materialName: string | undefined,
  index: number,
): string => {
  if (label && label.trim()) return label;
  const mat = (materialName || '').trim();
  if (mat && !isAutoGeneratedName(mat)) return mat;
  return `部位 ${index + 1}`;
};
