export const MOCK_PROJECT_ID = "1"; // From our mock projects in LeftSidebar

export const mockFolders = [
    {
        id: "f1",
        projectId: MOCK_PROJECT_ID,
        parentId: null,
        ancestors: [],
        name: "3D Models",
        isDeleted: false,
        deletedAt: null,
        createdAt: new Date("2023-01-01T10:00:00Z"),
    },
    {
        id: "f2",
        projectId: MOCK_PROJECT_ID,
        parentId: null,
        ancestors: [],
        name: "Architectural Plans",
        isDeleted: false,
        deletedAt: null,
        createdAt: new Date("2023-01-02T11:00:00Z"),
    },
    {
        id: "f3",
        projectId: MOCK_PROJECT_ID,
        parentId: "f1",
        ancestors: ["f1"],
        name: "Furniture",
        isDeleted: false,
        deletedAt: null,
        createdAt: new Date("2023-01-05T14:00:00Z"),
    },
    {
        id: "f4",
        projectId: MOCK_PROJECT_ID,
        parentId: "f1",
        ancestors: ["f1"],
        name: "Lighting",
        isDeleted: false,
        deletedAt: null,
        createdAt: new Date("2023-01-06T09:00:00Z"),
    },
];

export const mockAssets = [
    {
        id: "a1",
        projectId: MOCK_PROJECT_ID,
        folderId: null,
        ancestors: [],
        name: "Project Overview Presentation.pdf",
        type: "application/pdf",
        assetKind: "slide",
        size: 2500000, // 2.5 MB
        sourceApp: "3DSP",
        url: "#",
        thumbnailUrl: null,
        isDeleted: false,
        deletedAt: null,
        createdAt: new Date("2023-01-01T10:15:00Z"),
    },
    {
        id: "a2",
        projectId: MOCK_PROJECT_ID,
        folderId: "f1",
        ancestors: ["f1"],
        name: "House Structure.gltf",
        type: "model/gltf-binary",
        assetKind: "model",
        size: 15000000, // 15 MB
        sourceApp: "3DSS",
        url: "#",
        thumbnailUrl: null,
        isDeleted: false,
        deletedAt: null,
        createdAt: new Date("2023-01-02T12:00:00Z"),
    },
    {
        id: "a3",
        projectId: MOCK_PROJECT_ID,
        folderId: "f2",
        ancestors: ["f2"],
        name: "Floor Plan v1.png",
        type: "image/png",
        assetKind: "image",
        size: 800000, // 800 KB
        sourceApp: "3DSL",
        url: "#",
        thumbnailUrl: null,
        isDeleted: false,
        deletedAt: null,
        createdAt: new Date("2023-01-03T15:30:00Z"),
    },
    {
        id: "a4",
        projectId: MOCK_PROJECT_ID,
        folderId: "f3",
        ancestors: ["f1", "f3"],
        name: "Modern Sofa.gltf",
        type: "model/gltf-binary",
        assetKind: "model",
        size: 4500000, // 4.5 MB
        sourceApp: "3DSS",
        url: "#",
        thumbnailUrl: null,
        isDeleted: false,
        deletedAt: null,
        createdAt: new Date("2023-01-05T16:00:00Z"),
    },
    {
        id: "a5",
        projectId: MOCK_PROJECT_ID,
        folderId: "f3",
        ancestors: ["f1", "f3"],
        name: "Dining Table.obj",
        type: "model/obj",
        assetKind: "model",
        size: 3200000, // 3.2 MB
        sourceApp: "3DSS",
        url: "#",
        thumbnailUrl: null,
        isDeleted: false,
        deletedAt: null,
        createdAt: new Date("2023-01-05T17:15:00Z"),
    },
    {
        id: "a6",
        projectId: MOCK_PROJECT_ID,
        folderId: "f4",
        ancestors: ["f1", "f4"],
        name: "Pendant Light.gltf",
        type: "model/gltf-binary",
        assetKind: "model",
        size: 1200000, // 1.2 MB
        sourceApp: "3DSS",
        url: "#",
        thumbnailUrl: null,
        isDeleted: false,
        deletedAt: null,
        createdAt: new Date("2023-01-06T10:00:00Z"),
    },
];
