export const ALIAS_DICT = {
  // 家具
  "lowtable": { type: "家具", mainCategory: "テーブル", subCategory: "ローテーブル" },
  "low table": { type: "家具", mainCategory: "テーブル", subCategory: "ローテーブル" },
  "coffee table": { type: "家具", mainCategory: "テーブル", subCategory: "ローテーブル" },
  "dining table": { type: "家具", mainCategory: "テーブル", subCategory: "ダイニングテーブル" },
  "table": { type: "家具", mainCategory: "テーブル", subCategory: "" },
  "office chair": { type: "家具", mainCategory: "チェア", subCategory: "オフィスチェア" },
  "chair": { type: "家具", mainCategory: "チェア", subCategory: "チェア" },
  "lobby sofa": { type: "家具", mainCategory: "ソファ", subCategory: "ロビーチェア" },
  "sofa": { type: "家具", mainCategory: "ソファ", subCategory: "ソファ" },
  "bench": { type: "家具", mainCategory: "チェア", subCategory: "ベンチ" },
  "desk": { type: "家具", mainCategory: "デスク", subCategory: "" },
  "shelf": { type: "家具", mainCategory: "収納", subCategory: "シェルフ" },
  "planter": { type: "家具", mainCategory: "備品", subCategory: "プランター" },

  // 建築
  "wall": { type: "建築", mainCategory: "建築", subCategory: "壁" },
  "floor": { type: "建築", mainCategory: "建築", subCategory: "床" },
  "ceiling": { type: "建築", mainCategory: "建築", subCategory: "天井" },
  "door": { type: "建築", mainCategory: "建築", subCategory: "ドア" },
  "window": { type: "建築", mainCategory: "建築", subCategory: "窓" },
  "fence": { type: "建築", mainCategory: "外構", subCategory: "フェンス" },
  "handrail": { type: "建築", mainCategory: "外構", subCategory: "手すり" },
  "facade": { type: "建築", mainCategory: "外装", subCategory: "ファサード" },
  "partition": { type: "建築", mainCategory: "建具", subCategory: "パーティション" },
  "gate": { type: "建築", mainCategory: "外構", subCategory: "門扉" },
  "frame": { type: "建築", mainCategory: "建具", subCategory: "建具枠" },
  "panel": { type: "建築", mainCategory: "建具", subCategory: "パネル" },
  "slab": { type: "建築", mainCategory: "建築", subCategory: "床" },
  
  // Additional English Architecture keywords
  "villa": { type: "建築", mainCategory: "建築", subCategory: "住宅" },
  "home": { type: "建築", mainCategory: "建築", subCategory: "住宅" },
  "residence": { type: "建築", mainCategory: "建築", subCategory: "住宅" },
  "residential": { type: "建築", mainCategory: "建築", subCategory: "住宅" },
  "apartment": { type: "建築", mainCategory: "建築", subCategory: "集合住宅" },
  "mansion": { type: "建築", mainCategory: "建築", subCategory: "集合住宅" },
  "condominium": { type: "建築", mainCategory: "建築", subCategory: "集合住宅" },
  "condo": { type: "建築", mainCategory: "建築", subCategory: "集合住宅" },
  "office": { type: "建築", mainCategory: "建築", subCategory: "オフィス" },
  "building": { type: "建築", mainCategory: "建築", subCategory: "ビル" },
  "tower": { type: "建築", mainCategory: "建築", subCategory: "ビル" },
  "hotel": { type: "建築", mainCategory: "建築", subCategory: "ホテル" },
  "hospital": { type: "建築", mainCategory: "建築", subCategory: "病院" },
  "school": { type: "建築", mainCategory: "建築", subCategory: "学校" },
  "store": { type: "建築", mainCategory: "建築", subCategory: "店舗" },
  "shop": { type: "建築", mainCategory: "建築", subCategory: "店舗" },
  "facade": { type: "建築", mainCategory: "外装", subCategory: "ファサード" },
  "exterior": { type: "建築", mainCategory: "外観" },
  "interior": { type: "建築", mainCategory: "内観" },
  "plan": { type: "建築", mainCategory: "平面" },
  "elevation": { type: "建築", mainCategory: "立面" },
  "section": { type: "建築", mainCategory: "断面" },
  "site": { type: "建築", mainCategory: "配置" },
  "staircase": { type: "建築", mainCategory: "建築", subCategory: "階段" },
  "corridor": { type: "建築", mainCategory: "建築", subCategory: "廊下" },
  "entrance": { type: "建築", mainCategory: "建築", subCategory: "玄関" },
  "roof": { type: "建築", mainCategory: "建築", subCategory: "屋根" },
  "column": { type: "建築", mainCategory: "建築", subCategory: "柱" },
  "beam": { type: "建築", mainCategory: "建築", subCategory: "梁" },
  "opening": { type: "建築", mainCategory: "建具", subCategory: "開口" },
  "sash": { type: "建築", mainCategory: "建具", subCategory: "サッシ" },
  "curtain wall": { type: "建築", mainCategory: "外装", subCategory: "カーテンウォール" },

  // Additional Japanese Architecture keywords
  "マンション": { type: "建築", mainCategory: "建築", subCategory: "集合住宅" },
  "住宅": { type: "建築", mainCategory: "建築", subCategory: "住宅" },
  "戸建": { type: "建築", mainCategory: "建築", subCategory: "住宅" },
  "一戸建て": { type: "建築", mainCategory: "建築", subCategory: "住宅" },
  "別荘": { type: "建築", mainCategory: "建築", subCategory: "住宅" },
  "ビラ": { type: "建築", mainCategory: "建築", subCategory: "住宅" },
  "ヴィラ": { type: "建築", mainCategory: "建築", subCategory: "住宅" },
  "集合住宅": { type: "建築", mainCategory: "建築", subCategory: "集合住宅" },
  "アパート": { type: "建築", mainCategory: "建築", subCategory: "集合住宅" },
  "オフィス": { type: "建築", mainCategory: "建築", subCategory: "オフィス" },
  "事務所": { type: "建築", mainCategory: "建築", subCategory: "オフィス" },
  "商業施設": { type: "建築", mainCategory: "建築", subCategory: "店舗" },
  "店舗": { type: "建築", mainCategory: "建築", subCategory: "店舗" },
  "学校": { type: "建築", mainCategory: "建築", subCategory: "学校" },
  "病院": { type: "建築", mainCategory: "建築", subCategory: "病院" },
  "ホテル": { type: "建築", mainCategory: "建築", subCategory: "ホテル" },
  "ビル": { type: "建築", mainCategory: "建築", subCategory: "ビル" },
  "建物": { type: "建築", mainCategory: "建築", subCategory: "建築" },
  "外観": { type: "建築", mainCategory: "外観" },
  "内観": { type: "建築", mainCategory: "内観" },
  "立面": { type: "建築", mainCategory: "立面" },
  "断面": { type: "建築", mainCategory: "断面" },
  "平面": { type: "建築", mainCategory: "平面" },
  "配置": { type: "建築", mainCategory: "外構", subCategory: "配置" },
  "敷地": { type: "建築", mainCategory: "外構", subCategory: "敷地" },
  "玄関": { type: "建築", mainCategory: "建築", subCategory: "玄関" },
  "廊下": { type: "建築", mainCategory: "建築", subCategory: "廊下" },
  "階段": { type: "建築", mainCategory: "建築", subCategory: "階段" },
  "柱": { type: "建築", mainCategory: "建築", subCategory: "柱" },
  "梁": { type: "建築", mainCategory: "建築", subCategory: "梁" },
  "開口": { type: "建築", mainCategory: "建具", subCategory: "開口" },
  "建具": { type: "建築", mainCategory: "建具" },
  "サッシ": { type: "建築", mainCategory: "建具", subCategory: "サッシ" },

  // PC / display / keyboard
  "pc": { type: "家具", mainCategory: "備品", subCategory: "PC" },
  "display": { type: "家具", mainCategory: "備品", subCategory: "ディスプレイ" },
  "monitor": { type: "家具", mainCategory: "備品", subCategory: "モニター" },
  "keyboard": { type: "家具", mainCategory: "備品", subCategory: "キーボード" },

  "lobby": { detailCategory: "ロビー" }
};
